api.md
postrocessing -> postprocessing
=> Fixing small glitch example code typo

.prettierrc, example/public/index.html, example/src/App.js, package.json, src/EffectComposer.tsx, src/effects/ChromaticAberration.tsx, src/effects/DepthOfField.tsx, src/effects/Glitch.tsx, src/effects/Grid.tsx, src/effects/Outline.tsx, src/effects/SMAA.tsx, src/effects/SSAO.tsx, src/effects/Texture.tsx, src/util.tsx
I went through and updated the hook dependencies following this conversation.
https://github.com/react-spring/react-postprocessing/issues/17#issuecomment-668747791
There shouldn't be any breaking changes, but we should do some light verification before merging.
=> Updated hook dependencies to match linter recommendations

src/effects/Outline.tsx
This `console.log` statement was annoying me in my project :)
=> Remove unnecessary log

api.md
* Hash links for SSAO, Outline, SelectiveBloom and SMAA
* Fixes link to SSAO docs
=> Fixes API doc links

src/EffectComposer.tsx, src/effects/SSAO.tsx
Reverts pmndrs/react-postprocessing#66
=> Revert "Add disableNormalPass to EffectComposer props"

src/EffectComposer.tsx, src/effects/SSAO.tsx
Reverts pmndrs/react-postprocessing#75
=> Revert "Revert "Add disableNormalPass to EffectComposer props""

src/effects/SSAO.tsx
=> Fix SSAO return value

api.md
Change the old `react-postprocessing` imports to `@react-three/postprocessing`
=> Update imports in api.md

api.md
- removed dup SMAA description
=> tiltshift ssma docs

src/effects/Glitch.tsx
Fixes a memory leak where Glitch will recreate on prop update.
=> fix(Glitch): dispose on unmount

package.json, src/effects/SSR/index.tsx, src/effects/SSR/screen-space-reflections.js, yarn.lock
Fixes SSR for r151+ since the uv refactor frenzy which took out the ecosystem.
=> fix(SSR): support for r151+

docs/selection.mdx
=> docs: fix typo

src/EffectComposer.tsx
=> fix(EffectComposer): don't merge convolution effects

src/EffectComposer.tsx
Completes the fix for https://github.com/pmndrs/react-postprocessing/pull/242.
=> fix(EffectComposer): harden convolution check

src/effects/SSR/screen-space-reflections.js
Fixes an issue where postprocessing uniforms were redefined in the final SSR shader.
=> fix(SSR): remove duplicate chunks

src/effects/N8AO/EffectCompositer.js
=> fix(N8AO): compat for sRGB chunk renames

.eslintrc.json, .github/workflows/release.yml, CONTRIBUTING.md, package.json, yarn.lock
Removes Storybook and GitHub pages flows.
=> chore: remove storybook

src/util.tsx
=> fix: drop forwardRef in wrapEffect

package.json, src/EffectComposer.tsx, src/effects/ASCII.tsx, yarn.lock
Implements #319 and removes WebGL2 checks as WebGL 1 has since been removed.
=> fix(types): remove use of ambient three

package.json
=> fix: include dist folder in package files

package.json, tsconfig.json, vite.config.ts, yarn.lock
Follow-up to #325. Include non-duplicated type artifacts.
=> fix(types): emit types in build
