examples/src/demos/Bubbles/index.tsx, examples/src/demos/TakeControl/index.tsx, src/EffectComposer.tsx
In working on my own effects chain, I found some blurriness in textures that I eventually isolated to the `devicePixelRatio` not being set on the composer.
Switching over to `react-postprocessing`, it looks like it exhibits the same problem.
=> Respect devicePixelRatio

src/EffectComposer.tsx, yarn.lock
I figured out the issues that I was having the other day. This PR solves the normal map flickering on mount/remount as well as the postprocessing library blowing up on unmount.
When destructing props, using the spread `...` operator will create an new object every time. This was causing the useMemo to be invalidated every prop change since it was depending on `...props`. Instead, I dug into the postprocessing library and found the [actual constructor properties it supports.](https://github.com/vanruesc/postprocessing/blob/master/src/core/EffectComposer.js#L44-L48) By depending on these props explicitly, it doesn't cause volatile invalidation.
The `composer` object is not always defined and was causing issues with `addPass`, `setSize`, `etc` during unmount. I have guarded those invocations …
=> Now gracefully unmounting EffectComposer

src/util.tsx
Before, in `wrapEffect` the `opacity` and `blendFunction` props that are present in all effects, were inacessible, even though they were set in inside `wrapEffect`
this PR fixes it, so u can use `opacity` prop without errors
=> Fix opacity and blendFunction types in wrapEffect

src/EffectComposer.tsx, src/util.tsx
Using the `isWebGL2Available()` function from Three.js, this fixes things on Safari until they support webgl2.
Fixes #28
=> Fix multisampling when webgl2 is not supported

README.md, examples/config-overrides.js, examples/package.json, examples/src/demos/Bubbles/index.tsx, examples/src/demos/Selection/index.tsx, examples/src/demos/TakeControl/Effects.tsx, examples/src/demos/TakeControl/Scene.tsx, examples/src/demos/TakeControl/index.tsx, package.json, yarn.lock
Renamed package to match the new `@react-three/*` namespace.
❗ These packages need to be published at their current version. ❗
❗ I have only renamed the dependencies in the various packages, I have not adjusted the version number. If we bump the version before these PRs get merged, we will need to also change it in each package within the ecosystem. ❗ 
- You may need to add the `--access public` option or something similar since scoped packages are by default private. See https://docs.npmjs.com/creating-and-publishing-scoped-public-packages#publishing-scoped-public-packages for more details
**Note:** Some of these packages have dependencies on each other. If you run into a "package not found" error when attempting to `yarn install`, you might need to run through these steps on a dependent …
=> renamed package

.eslintrc.json, examples/src/demos/Bubbles/index.tsx, examples/src/demos/TakeControl/Effects.tsx, src/effects/ColorAverage.tsx, src/effects/Glitch.tsx, src/effects/Pixelation.tsx, src/effects/SSAO.tsx, src/effects/Texture.tsx, src/util.tsx, tsconfig.json
Attempting to assign a `ref` to any of these `ForwardRefExoticComponent` types will fail:
The reason is that `ref` doesn't actually exist as a property on `ForwardRefExoticComponent`, so we should avoid using that type. The better way to type `forwardRef` components is to use the generic arguments in `forwardRef<T, P>`, where `T` is the ref type and `P` is the props type.
See https://stackoverflow.com/questions/60052450/in-react-using-typescript-how-do-i-pass-a-ref-to-a-custom-component-using-reff for more info.
This PR also fixes the Netlify deploy, which was broken by the package rename (some aliases needed to be updated). Once the deploy started working, I noticed the examples were crashing on startup due to a change in [`useResource`](https://github.com/pmndrs/react-three-fiber/commit/ …
=> Fix type definitions for forwardRef components

api.md
This typo cost us lives of at least 30 frames per second. 😔
=> Docs: Fix typo

api.md
Fix for a tiny error in the API docs for Vignette - `eskil` is written as `eskill`.
This component is an export of wrapperEffect() around https://github.com/vanruesc/postprocessing/blob/main/src/effects/VignetteEffect.js, so the expected API can be checked there.
Example of the component working with the correct prop name - https://codesandbox.io/s/eskil-vignette-f4yem
=> Update docs to fix eskil prop for Vignette 

src/effects/SSAO.tsx, types/postprocessing.d.ts
[Looking at this example](https://codesandbox.io/s/zxpv7?file=/src/App.js:2301-2367), I noticed that the properties `intensity` and `color` were missing from the `SSAOEffect` definition's constructor parameters. I've added them with the corresponding documentation from [the postprocessing website](https://vanruesc.github.io/postprocessing/public/docs/class/src/effects/SSAOEffect.js~SSAOEffect.html).
=> Add intensity and color to SSAO parameters.

src/effects/GammaCorrection.tsx, src/index.tsx
Per [this discussion](https://discord.com/channels/740090768164651008/741754170310131763/922283014476673074), adding gamma correction effect as export to react-pp.
I'm still wondering if this is the best solution to the problem encountered, as it seems like some output encoding issue involving render targets, but exporting here does provide a knob for an issue I and @richczhou encountered where color/tonemapping is off in certain custom shader scenes ([example](https://codesandbox.io/s/react-pp-weirdness-forked-stsyx?file=/src/App.js)).
this is my first contribution so I'm not sure if any other files need adjustments (e.g. postprocessing.d.ts ?)
=> added gamma correction effect

package.json, src/Selection.tsx, yarn.lock
Fixes #120 by dropping lodash-es which is ESM-only.
=> fix(Selection): remove ESM-only lodash/without

src/effects/Glitch.tsx, types/postprocessing.d.ts
Hello everyone! 👋
I was not able to pass a number value to the `mode` prop at the `Glitch` component. 
I could whether decide to change the type to just a `number` type or add the values to the `GlitchMode` declarations and adjust the `mode` property. I preferred this solution as now the `mode` prop will only accept `0 | 1 | 2 | 3`.
=> fix Glitch and GlitchMode typings

src/util.tsx
This PR fixes the current workflow when the effect wrapper's prop blendFunction is overwritten with defaultBlendMode if it is equal to 0, which is the value of BlendFunction.SKIP
=> fix: allow BlendFunction.SKIP in wrapEffect

package.json, yarn.lock
Unpins the postprocessing dependency to stay within the current major (https://github.com/pmndrs/react-postprocessing/issues/124#issuecomment-1117789682).
=> fix(deps): unpin postprocessing

package.json, rollup.config.js
Drops the unused `react-dom` peer dependency and fixes issues with Node target resolution.
=> fix: drop react-dom peer dep, correctly flag targets

README.md, api.md
This PR points URLs for documentation at the https://github.com/pmndrs/postprocessing repo rather than the old https://github.com/vanruesc/postprocessing repo and the https://pmndrs.github.io/postprocessing/public/docs/ site instead of the (broken) https://vanruesc.github.io/postprocessing/public/docs/ site.
:)
=> Fix Links (vanruesc --> pmndrs)

api.md, src/effects/TiltShift2.tsx
**Improvements:**
- Sizes are now defined as a function of screen dimensions. Before `blur` and `gradient` sizes were defined in pixel values but now are in line with "start" and "end" which are defined as percentages of screen space. 
- `gradient` prop / uniform is renamed to `taper` to clarify this distinction
- You can go over 100% for the sizes and it should still work
- Blur size and focus area are now normalized by the size of the diagonal, this makes the effect (1) screen size adaptive if canvas size is changing (2) more consistent effect across portrait and landscape modes (3) more resilient to canvas `dpr` changes
- Introduced `sampleCount` so we can adjust quality & effect cost at runtime
- Added `#define` for `MAX_ITERATIONS`, which means it's impossible to have higher than 100 …
=> improvements to TiltShift2 for adaptive size and quality

.github/workflows/main.yml
with semantic-release, building check is now also/already part of release.yml pipeline: https://github.com/pmndrs/react-postprocessing/blob/9d1f77e454a43c0d5411734248ad8eef8e508ed6/.github/workflows/release.yml#L22
=> chore(pipeline): simplifying ci

src/effects/GodRays.tsx
Allows `GodRays` to accept a mutable reference to a mesh so it can be declared in JSX.
=> feat(GodRays): accept mesh ref

src/effects/GodRays.tsx, src/util.tsx
When the effect type definitions were generated:
- with the `wrapEffect` function 
- and have default props passed to the function as the second argument
the types were incorrect.
Effects that were broken:
- Bloom
- Noise
- Scanline
- TiltShift
- TiltShift2
=> fix: missing effect type definitions

src/util.tsx
Fixes a regression from #179 where `BlendEffect.opacity` is written to rather than `BlendEffect.opacity.value`.
https://github.com/pmndrs/postprocessing/blob/main/src/effects/blending/BlendMode.js#L113
=> fix(wrapEffect): set blendmode opacity.value

src/EffectComposer.tsx
Splits JSX children into an `EffectPass` or preserves them if they implement `Pass`. Other children are excluded and have no effect.
```jsx
<EffectComposer>
<Effect />
<Effect />
<Pass />
<Effect />
</EffectComposer>
// [EffectPass([Effect, Effect]), Pass, EffectPass([Effect])]
```
=> fix(EffectComposer): split effects and passes

package.json
Unpins peer deps. This should at least not specify a patch version, but since this is just wrapping postprocessing, we yield to its requirements.
=> fix: unpin peer deps

src/effects/Outline.tsx
Fixes #205 by untracking props for the effect implementation. This should use `wrapEffect` instead to prevent issues like this.
=> fix(Outline): don't stale invalidate

src/effects/Glitch.tsx
Fixes Glitch's `chromaticAbberationOffset` prop by creating a target for it.
=> fix(Glitch): set non-null chromatic offset

src/effects/DepthOfField.tsx
Hi I found that DepthOfField Component has a Texture Memory leak
so I fix it in PR
you can check memory leak this [codeSandbox](https://codesandbox.io/s/depth-test-example-forked-4fsj27)
Every update of parameter, texture count increase infinitely
=> fix(DepthOfField): cleanup memory leak

vite.config.ts
Fixes #238.
Re-enables `preserveModules` to facilitate coarse module traversal for dependencies.
=> fix: split up bundle for tree-shaking

src/effects/ToneMapping.tsx
`<ToneMapping />` redefines tonemapping chunks which doesn't combine well with other chunks.
Split it into a separate pass until we have a mechanism for fixing this.
=> fix(ToneMapping): configure as convolution effect

src/EffectComposer.tsx
Hardens effect pass merging to not skip effects when splitting convolution effects.
=> fix(EffectComposer): don't skip effects when backtracking

src/EffectComposer.tsx
Follow-up to #248, accounts for inverse case.
=> fix(EffectComposer): don't merge when convolution is head

src/effects/Outline.tsx
Fixes a memory leak in `Outlines`.
=> fix(Outline): dispose on unmount

src/effects/DepthOfField.tsx
This should call the `DepthOfFieldEffect.maskFunction`  setter https://github.com/pmndrs/postprocessing/blob/v6.34.1/src/effects/DepthOfFieldEffect.js#L281
It's my first contribution to the postprocessing stack so please before merging double check that this does not cause any issue in other corner cases.
Fix #261
=> fix(DoF): mask function

src/effects/ToneMapping.tsx
Fixes #305 with a revert of #245. Convolution effects since lead to separate effect passes or severe performance ramifications when using tonemapping in projects, which is the end of a standard PBR workflow.
=> fix(ToneMapping): remove use of CONVOLUTION attribute

src/effects/SSR/screen-space-reflections.js
`copyFramebufferToTexture()` changed its signature in r165 https://github.com/mrdoob/three.js/pull/28329
=> fix: avoid warnings with Three 165+ with screen-space-reflections.js

package.json
Narrows peer deps as React 19 is not backwards compatible. See #302.
=> fix: narrow React peer deps

docs/effects/sepia.mdx
The `Sepia`'s `intensity` prop should be a `Number` not a `Boolean` 👀
Just updated that in the docs 😄👌
=> docs: `Sepia` effect `intensity` type to `Number`

docs/effect-composer.mdx
DisableNormalPass does not exist.
right ? 
I use "@react-three/postprocessing": "^2.16.2",
```
"dependencies": {
"@react-spring/three": "^9.7.3",
"@react-three/drei": "^9.105.1",
"@react-three/fiber": "^8.16.1",
"@react-three/postprocessing": "^2.16.2",
"gltfjsx": "^6.2.16",
"maath": "^0.10.7",
"next": "14.1.4",
"prettier": "^3.2.5",
"react": "^18",
"react-dom": "^18",
"three": "^0.163.0"
},
```
=> docs: update EffectComposer props

src/effects/SelectiveBloom.tsx
Fixes #111 
The `ignoreBackground` and `inverted` props of `SelectiveBloom` were not being applied, causing the selective bloom effect to work incorrectly, particularly when using an HDRI environment map. This issue is further detailed in [this GitHub issue](https://github.com/pmndrs/react-postprocessing/issues/111).
As shown in the images below:
- **Left:** Before the fix, the bloom effect is applied to bright areas of the background image and parts of the cube not selected for the bloom effect.
- **Right:** After the fix, the selective bloom effect is working as expected, with the background and cube affected correctly based on the props.
The suggested solution in issue #111 involved using emissive materials with values above the 0-1 RGB range and setting a high luminanceThreshold to …
=> fix(SelectiveBloom): apply ignoreBackground and inverted props

src/EffectComposer.tsx, src/effects/ASCII.tsx, src/effects/SelectiveBloom.tsx
=> fix(types): remove use of ambient three

.npmignore
Fixes #324. Removes `dist` from ignored directories.
=> fix: include dist folder in release artifacts
